### ISSUE TITLE
Changing an Ember.Array-based QP does not fire queryParamsDidChange

### ISSUE THREAD

**Issue by mwpastore** [offirgolan/ember-parachute#28] opened 2017-07-14 22:16 UTC
Using `pushObject` to add an element to an Ember.Array-backed QP does not fire the corresponding `queryParamsDidChange` hook.

**Comment by buschtoens** [comment] 2017-07-14 22:31
Same goes for keys on objects, I would guess.

**Comment by offirgolan** [comment] 2017-07-24 04:33
The demo has an array backed QP and it seems to be working without any problem. @mwpastore @buschtoens can you guys recreate these in a twiddle?

**Comment by buschtoens** [comment] 2017-07-25 10:11
Ya, sure: [Twiddle](https://ember-twiddle.com/75b2ce2383f8b6021d2f99e2f5a3818f?openFiles=templates.application.hbs%2C&route=%2F%3Fpage%3D21%26tags%3D)

**Comment by offirgolan** [comment] 2017-07-25 16:48
Ah it looks like the hook is getting called but `shouldRefresh` is false for some reason.

**Comment by offirgolan** [comment] 2017-07-25 17:08
@buschtoens you forgot to add `refresh: true` on tags 😛. Everything works as intended as far as I can tell.

**Comment by buschtoens** [comment] 2017-07-25 17:39
Yep. Looks good. :man_facepalming: 

@mwpastore Do you concur?

**Comment by mwpastore** [comment] 2017-07-25 17:44
@buschtoens Thanks for putting the Twiddle together. Let me go back to my original use case and try to figure out what's going on here.

**Comment by offirgolan** [comment] 2017-08-16 23:14
Closing as this issue has been abandoned. Feel free to reopen if needed.

**Closed by offirgolan** 2017-08-16 23:14 UTC
